# -*- coding: utf-8 -*-
"""SCT_DS_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jKp8lOGA6BstM8CNxW4FSFVD5A6jd_S1
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
from google.colab import files

uploaded = files.upload()
file_name = list(uploaded.keys())[0]

data = pd.read_csv(file_name)

expected_cols = ["Session_Duration (hours)", "Calories_Burned"]
if not all(col in data.columns for col in expected_cols):
    raise KeyError(f"Expected columns not found: {expected_cols}")

data = data[expected_cols].dropna()
data = data.sort_values(by="Calories_Burned")

if data.empty:
    raise ValueError("The dataset is empty after cleaning!")

plt.figure(figsize=(14, 6))

sns.kdeplot(x=data["Session_Duration (hours)"], color='navy', linewidth=2, label='Overall Trend')

zones = [
    ((0.25, 1.0), 'lightskyblue', 'Short Sessions'),
    ((1.0, 1.5), 'mediumseagreen', 'Moderate Sessions'),
    ((1.5, 2.25), 'lightcoral', 'Long Sessions'),
]

for clip_range, color, label in zones:
    sns.kdeplot(
        x=data["Session_Duration (hours)"],
        fill=True,
        alpha=0.5,
        clip=clip_range,
        color=color,
        label=label
    )

plt.xlabel("Session Duration (hours)", fontsize=12)
plt.ylabel("Calories Burned (in thousands)", fontsize=12)
plt.title("KDE Plot: Calories Burned vs Session Duration", fontsize=14)
plt.legend()
plt.gca().yaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'{int(x * 1000)}'))
plt.tight_layout()
plt.show()